//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual_Sort.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visual_Sort.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bogo Sort = Monkey Sort, Stupid Sort.
        /// </summary>
        internal static string strBogoSort {
            get {
                return ResourceManager.GetString("strBogoSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bozo Sort.
        /// </summary>
        internal static string strBozoSort {
            get {
                return ResourceManager.GetString("strBozoSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bubble Sort (original version).
        /// </summary>
        internal static string strBubbleSort1 {
            get {
                return ResourceManager.GetString("strBubbleSort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bubble Sort (premature termination).
        /// </summary>
        internal static string strBubbleSort2 {
            get {
                return ResourceManager.GetString("strBubbleSort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bubble Sort (comparative reduction).
        /// </summary>
        internal static string strBubbleSort3 {
            get {
                return ResourceManager.GetString("strBubbleSort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка подсчетом.
        /// </summary>
        internal static string strCountingSort {
            get {
                return ResourceManager.GetString("strCountingSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dotes.
        /// </summary>
        internal static string strDotes {
            get {
                return ResourceManager.GetString("strDotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на draw lines.
        /// </summary>
        internal static string strDrawLines {
            get {
                return ResourceManager.GetString("strDrawLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на fill rectangles.
        /// </summary>
        internal static string strFillRectangles {
            get {
                return ResourceManager.GetString("strFillRectangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка вставками.
        /// </summary>
        internal static string strInsertionSort {
            get {
                return ResourceManager.GetString("strInsertionSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lines.
        /// </summary>
        internal static string strLines {
            get {
                return ResourceManager.GetString("strLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка слиянием.
        /// </summary>
        internal static string strMergeSort {
            get {
                return ResourceManager.GetString("strMergeSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string strNumberZero {
            get {
                return ResourceManager.GetString("strNumberZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на random.
        /// </summary>
        internal static string strRandom {
            get {
                return ResourceManager.GetString("strRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random Sort.
        /// </summary>
        internal static string strRandomSort {
            get {
                return ResourceManager.GetString("strRandomSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sorted forward.
        /// </summary>
        internal static string strSortedForward {
            get {
                return ResourceManager.GetString("strSortedForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sorted reverse.
        /// </summary>
        internal static string strSortedReverse {
            get {
                return ResourceManager.GetString("strSortedReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trippel Sort = Stooge Sort (original version).
        /// </summary>
        internal static string strTrippelSort1 {
            get {
                return ResourceManager.GetString("strTrippelSort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trippel Sort = Stooge Sort (comparative reduction).
        /// </summary>
        internal static string strTrippelSort2 {
            get {
                return ResourceManager.GetString("strTrippelSort2", resourceCulture);
            }
        }
    }
}
